### ISSUE TITLE
Riak admin services shows blank list

### ISSUE THREAD

**Issue by azowarg** [OpenRiak/riak#3]
Hello, I came to this repo from [this](https://github.com/basho/riak_kv/issues/1889) issue. 
I just wanted to let you know that for some reason in the nhs 3.2.2 version, the command ```riak admin services``` shows in the output blank list.
```bash
root@riak-0:/var/lib/riak# riak admin services
[]
```
But I am sure that the service works without problem and for example I can check for it with another command.
```bash
root@riak-0:/var/lib/riak# riak admin wait-for-service riak_kv
riak_kv is up
```

**Comment by martinsumner** [comment]
Apologies, this got missed by me and forgotten about.

I can confirm the issue:

```
% riak admin services
[]
% riak rpc riak_core_node_watcher services
[riak_kv, riak_pipe, riak_repl]
```

There is a workaround to use the second command (which is what the admin script is doing behind the scenes):

https://github.com/OpenRiak/riak/blob/nhse-develop/rel/files/riak-admin#L785-L793

So why the admin script doesn't work directly .... I don't know.

@hmmr - you've fixed problems like this before, do you know?

**Comment by martinsumner** [comment]
```
services)
        if [ $# -ne 1 ]; then
            echo "Usage: $SCRIPT $1"
            echo ""
            echo "Lists the services available on the node. See also: wait-for-service"
            exit 1
        fi
        
        SERVICES=`"${PLATFORM_BIN_DIR}/riak" rpc riak_core_node_watcher services || :`
        echo $SERVICES
        ;;
```

This works - but why is this necessary?

I assume I'm missing something obvious.

**Comment by hmmr** [comment]
There appears to be an issue with passing arguments to `rpc`, to deal with which there was an alternative version of `rpc`: https://github.com/OpenRiak/riak/blob/nhse-develop/rel/files/lib.sh#L28-L32.

All in all, replacing `rpc` with `rpc_raw` in the call to `rpc riak_core_node_watcher services` should be sufficient.

**Comment by hmmr** [comment]
Here's a PR: https://github.com/OpenRiak/riak/pull/11 for that.
